### ISSUE TITLE
Present "undo" when deleting an army or unit

### ISSUE THREAD

**Issue by sethladd** [matanlurey/hquplink-archived#39]
So I didn't realize that "swipe" meant "delete" until it was too late.

If possible, I'd love to be able to undo a "swipe to delete a unit". I think gmail has a pattern for this.

**Comment by matanlurey** [comment]
Agreed, has happened to me too. I am going to add an "undo" option for armies and units. It's probably not worth adding one for more minor things, like upgrades, since the cost of re-adding it is small.

**Comment by matanlurey** [comment]
Fixed at MASTER.
