### ISSUE TITLE
Not obvious how to proceed after create army screen

### ISSUE THREAD

**Issue by sethladd** [matanlurey/hquplink-archived#42]
My natural instinct is to press a button at the bottom of the screen with an action like create. But I later noticed a disc icon in upper right. Which is kind of far away from my thumb. I'm also curious if the disk icon means save to a lot of people.

**Comment by matanlurey** [comment]
Can you give me an example of an app with a flow that makes more sense?

I tried a couple popular apps (on Android, at least) and they all seem to use the top-level icon approach. We could obviously (easily) change the icon!

**Comment by matanlurey** [comment]
Archiving this repository in favor of a new one.
