### ISSUE TITLE
Make "unlimited" points at the end, not beginning, of the bar

### ISSUE THREAD

**Issue by sethladd** [matanlurey/hquplink-archived#43]
I'm not sure how to suggest a fix for this. But choosing unlimited points set the bar all the way to the left which looks like I said it to zero.

**Comment by matanlurey** [comment]
Yeah, this is a bit of a leaky abstraction that shows the fact that 0 is the same as unlimited. I can make it so the last value is considered unlimited instead. Thanks for the suggestion!

**Comment by matanlurey** [comment]
Or maybe even hide the slider when unlimited is used.
